name: CI

on:
  push:

jobs:
  build:
    name: Build
    uses: spacelift-io/flows-community-registry/.github/workflows/build-app-version.yml@main

  release:
    name: Release
    needs: build
    secrets: inherit
    uses: spacelift-io/flows-community-registry/.github/workflows/release-app-version.yml@main
